# @format
name: Compress Media Files

on:
    push:
        branches: [main]

jobs:
    compress_media:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.5.2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 17
            - name: npm install
              run: npm ci
            - name: compress media
              run: node index.js
            - name: push to another branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: serve
                  FOLDER: web
                  TARGET_DIR: web
                  MESSAGE: 'Add new files 🎉'
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
